# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 14:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('naslov', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bolezni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkb10', models.CharField(max_length=45)),
                ('naziv', models.CharField(max_length=45)),
                ('alergija', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('sifra', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Posta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField()),
                ('kraj', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pregled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opombe', models.CharField(max_length=2048)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sifra', models.CharField(max_length=1024)),
                ('naslov', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ustanova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('naslov', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zdravilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdravilo', models.CharField(max_length=100)),
                ('navodila', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Zdravnik',
            fields=[
                ('uporabnik_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpo.Uporabnik')),
                ('naziv', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('tpo.uporabnik',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='uporabnik',
            name='ambulanta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Ambulanta'),
        ),
        migrations.AddField(
            model_name='uporabnik',
            name='posta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Posta'),
        ),
        migrations.AddField(
            model_name='uporabnik',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Roles'),
        ),
        migrations.AddField(
            model_name='ambulanta',
            name='ustanova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Ustanova'),
        ),
        migrations.AddField(
            model_name='pregled',
            name='zdravnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Zdravnik'),
        ),
    ]
