# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 19:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('naslov', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bolezni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkb10', models.CharField(max_length=45)),
                ('naziv', models.CharField(max_length=45)),
                ('alergija', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('sifra', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Meritev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50)),
                ('enota', models.CharField(max_length=50)),
                ('normalno_min', models.FloatField()),
                ('normalno_max', models.FloatField()),
                ('nenormalno_min', models.FloatField()),
                ('nenormalno_max', models.FloatField()),
                ('nemogoce_min', models.FloatField()),
                ('nemogoce_max', models.FloatField()),
                ('cas_merjenja', models.CharField(max_length=100)),
                ('vrednost_meritve', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Osebje',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ime', models.CharField(max_length=100)),
                ('priimek', models.CharField(max_length=100)),
                ('sifra', models.IntegerField()),
                ('stevilka', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Posta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField()),
                ('kraj', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pregled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opombe', models.CharField(max_length=2048)),
                ('datum', models.DateField()),
                ('datum_naslednjega', models.DateField()),
                ('bolezen', models.ManyToManyField(to='tpo.Bolezni')),
                ('dieta', models.ManyToManyField(to='tpo.Dieta')),
                ('meritve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Meritev')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ime', models.CharField(max_length=100)),
                ('priimek', models.CharField(max_length=100)),
                ('datum_rojstva', models.DateField()),
                ('kraj_rojstva', models.CharField(max_length=50)),
                ('naslov', models.CharField(max_length=100)),
                ('st_zzzs', models.IntegerField()),
                ('spol', models.CharField(max_length=1)),
                ('krvna_skupina', models.CharField(max_length=3)),
                ('ambulanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Ambulanta')),
                ('bolezni', models.ManyToManyField(to='tpo.Bolezni')),
                ('meritev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Meritev')),
                ('posta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Posta')),
                ('pregledi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Pregled')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Roles')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ustanova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('naslov', models.CharField(max_length=100)),
                ('posta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Posta')),
            ],
        ),
        migrations.CreateModel(
            name='Zdravilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdravilo', models.CharField(max_length=100)),
                ('navodila', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Zdravnik',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ime', models.CharField(max_length=100)),
                ('priimek', models.CharField(max_length=100)),
                ('sifra', models.IntegerField()),
                ('naziv', models.CharField(max_length=50)),
                ('tip', models.CharField(max_length=50)),
                ('ambulanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Ambulanta')),
                ('medicinske_sestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Osebje')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Roles')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='uporabnik',
            name='zdravila',
            field=models.ManyToManyField(to='tpo.Zdravilo'),
        ),
        migrations.AddField(
            model_name='uporabnik',
            name='zdravnik',
            field=models.ManyToManyField(to='tpo.Zdravnik'),
        ),
        migrations.AddField(
            model_name='pregled',
            name='zdravilo',
            field=models.ManyToManyField(to='tpo.Zdravilo'),
        ),
        migrations.AddField(
            model_name='pregled',
            name='zdravnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Zdravnik'),
        ),
        migrations.AddField(
            model_name='osebje',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Roles'),
        ),
        migrations.AddField(
            model_name='bolezni',
            name='zdravilo',
            field=models.ManyToManyField(to='tpo.Zdravilo'),
        ),
        migrations.AddField(
            model_name='ambulanta',
            name='posta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Posta'),
        ),
        migrations.AddField(
            model_name='ambulanta',
            name='ustanova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpo.Ustanova'),
        ),
    ]
