# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdravnik',
            name='sprejema_paciente',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='ambulanta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tpo.Ambulanta'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='bolezni',
            field=models.ManyToManyField(blank=True, to='tpo.Bolezni'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='datum_rojstva',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='ime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='kraj_rojstva',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='krvna_skupina',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='meritev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpo.Meritev'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='naslov',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='posta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpo.Posta'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='pregledi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpo.Pregled'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='priimek',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='spol',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='st_zzzs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='zdravila',
            field=models.ManyToManyField(blank=True, to='tpo.Zdravilo'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='zdravnik',
            field=models.ManyToManyField(blank=True, to='tpo.Zdravnik'),
        ),
        migrations.AlterField(
            model_name='zdravnik',
            name='ambulanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpo.Ambulanta'),
        ),
        migrations.AlterField(
            model_name='zdravnik',
            name='ime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zdravnik',
            name='medicinske_sestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpo.Osebje'),
        ),
        migrations.AlterField(
            model_name='zdravnik',
            name='naziv',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='zdravnik',
            name='priimek',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zdravnik',
            name='sifra',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='zdravnik',
            name='tip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
