# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0002_auto_20160409_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uporabnik',
            name='ambulanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpo.Ambulanta'),
        ),
    ]
