# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0003_auto_20160409_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uporabnik',
            name='st_zzzs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
